"""add lease_agreements table

Revision ID: 18bf506932ee
Revises: c1f8b6a3d9e2
Create Date: 2026-02-09 21:21:40.742326

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "18bf506932ee"
down_revision: Union[str, None] = "c1f8b6a3d9e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lease_agreements",
        sa.Column("id", sqlmodel.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.AutoString(), nullable=False),
        sa.Column("property_id", sqlmodel.AutoString(), nullable=False),
        sa.Column("original_url", sqlmodel.AutoString(), nullable=False),
        sa.Column("signed_url", sqlmodel.AutoString(), nullable=True),
        sa.Column(
            "status", sa.Enum("UNSIGNED", "SIGNED", name="leasestatus"), nullable=False
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("rent_amount", sa.Float(), nullable=True),
        sa.Column("uploaded_by_landlord", sa.Boolean(), nullable=False),
        sa.Column("signed_uploaded_by", sqlmodel.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lease_agreements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lease_agreements_property_id"), ["property_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lease_agreements_tenant_id"), ["tenant_id"], unique=True
        )

    with op.batch_alter_table("payment_dispute_messages", schema=None) as batch_op:
        batch_op.alter_column(
            "body",
            existing_type=sa.TEXT(),
            type_=sqlmodel.AutoString(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_dispute_messages", schema=None) as batch_op:
        batch_op.alter_column(
            "body",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )

    with op.batch_alter_table("lease_agreements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lease_agreements_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_lease_agreements_property_id"))

    op.drop_table("lease_agreements")
    # ### end Alembic commands ###
