"""add_tenant_password_hash

Revision ID: 2c894ee763f5
Revises: 2f4cb0e26672
Create Date: 2025-12-31 21:08:31.468688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c894ee763f5"
down_revision: Union[str, None] = "2f4cb0e26672"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.add_column(sa.Column("password_hash", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.drop_column("password_hash")

    # ### end Alembic commands ###
