"""add_payment_receipt_and_verifying_status

Revision ID: a95e846d7956
Revises: 2c894ee763f5
Create Date: 2025-12-31 22:25:21.736577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a95e846d7956"
down_revision: Union[str, None] = "2c894ee763f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("receipt_url", sqlmodel.AutoString(), nullable=True)
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=8),
            type_=sa.Enum(
                "UPCOMING",
                "PENDING",
                "ON_TIME",
                "LATE",
                "OVERDUE",
                "WAIVED",
                "VERIFYING",
                name="paymentstatus",
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "UPCOMING",
                "PENDING",
                "ON_TIME",
                "LATE",
                "OVERDUE",
                "WAIVED",
                "VERIFYING",
                name="paymentstatus",
            ),
            type_=sa.VARCHAR(length=8),
            existing_nullable=False,
        )
        batch_op.drop_column("receipt_url")

    # ### end Alembic commands ###
