"""add rejection_reason to payments

Revision ID: b8164dad9fc4
Revises: bfae22a1f527
Create Date: 2026-02-09 14:15:31.374419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b8164dad9fc4"
down_revision: Union[str, None] = "bfae22a1f527"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("rejection_reason", sqlmodel.AutoString(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_column("rejection_reason")

    # ### end Alembic commands ###
