"""add tenant notifications table

Revision ID: d2c5dfbdbe89
Revises: 7a9d4a8e1b2c
Create Date: 2026-06-10 21:13:06.060062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c5dfbdbe89'
down_revision: Union[str, None] = '7a9d4a8e1b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('PAYMENT_RECEIPT_REJECTED', 'PAYMENT_DISPUTE_MESSAGE', 'MAINTENANCE_REQUEST_UPDATED', 'MAINTENANCE_COMMENT_CREATED', 'PAYMENT_REMINDER', 'LEASE_SIGNED', 'LEASE_REJECTED', name='tenantnotificationtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('property_id', sa.String(), nullable=True),
    sa.Column('maintenance_request_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_notifications_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_notifications_tenant_id'))

    op.drop_table('tenant_notifications')
    # ### end Alembic commands ###
